apiVersion: v1
data:
  filebeat.yml: |

    setup:
      ilm.enabled: false
      template.enabled: false
      dashboards.enabled: false
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          include_annotations: ["co.elastic.logs/enabled"]
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            enabled: false
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
          templates:
            - condition:
                equals:
                  kubernetes.namespace: "ingress-nginx"
              config:
                - module: nginx
                  access:
                    enabled: false
                  error:
                    enabled: false
                  ingress_controller:
                    enabled: true
                    input:
                      type: container
                      paths:
                        - /var/log/containers/*${data.kubernetes.container.id}.log
            - condition:
                equals:
                  kubernetes.namespace: "app-emprego"
              config:
                - module: nginx
                  access:
                    enabled: true
                    input:
                      type: container
                      pipeline: filebeat-7.16.1-appemprego-access-pipeline
                      paths:
                        - /var/log/containers/*${data.kubernetes.container.id}.log
                  error:
                    enabled: false
                  ingress_controller:
                    enabled: false
                    input:
                      type: container
                      paths:
                        - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - drop_fields:
          when:
            has_fields:
              ['agent.ephemeral_id']
          fields:
            - 'agent.ephemeral_id'
            - 'agent.hostname'
            - 'agent.id'
            - 'agent.name'
            - 'container.id'
            - 'container.runtime'
            - 'ecs.version'
            - 'host.name'
            - 'input.type'
            - 'kubernetes.labels.app_kubernetes_io/instance'
            - 'kubernetes.labels.app_kubernetes_io/managed-by'
            - 'kubernetes.labels.app_kubernetes_io/name'
            - 'kubernetes.labels.app_kubernetes_io/version'
            - 'kubernetes.labels.docker_app_pt/environment'
            - 'kubernetes.labels.docker_app_pt/name'
            - 'kubernetes.labels.helm_sh/chart'
            - 'kubernetes.labels.pod-template-hash'
            - 'kubernetes.namespace_labels.cattle_io/creator'
            - 'kubernetes.namespace_labels.field_cattle_io/projectId'
            - 'kubernetes.namespace_uid'
            - 'kubernetes.node.labels.beta_kubernetes_io/arch'
            - 'kubernetes.node.labels.beta_kubernetes_io/os'
            - 'kubernetes.node.labels.kubernetes_io/arch'
            - 'kubernetes.node.labels.kubernetes_io/os'
            - 'kubernetes.node.labels.kubernetes_io/hostname'
            - 'kubernetes.node.labels.node-role_kubernetes_io/controlplane'
            - 'kubernetes.node.labels.node-role_kubernetes_io/etcd'
            - 'kubernetes.node.labels.node-role_kubernetes_io/worker'
            - 'kubernetes.node.name'
            - 'kubernetes.node.uid'
            - 'kubernetes.pod.uid'
            - 'kubernetes.replicaset.name'
            - 'stream'
          ignore_missing: true

    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
      username: "${FILEBEAT_USERNAME:filebeat_writer}"
      password: "${FILEBEAT_PASSWORD:changeme}"
      indices:
        - index: "filebeat-k8s-%{[kubernetes.namespace]:unknown}-%{[kubernetes.container.name]:unknown}"
          when:
            not.equals.kubernetes.namespace: "ingress-nginx"

        - index: "filebeat-k8s-%{[kubernetes.namespace]}"
          when:
            equals.kubernetes.namespace: "ingress-nginx"
      # index: "filebeat-k8s-%{[kubernetes.namespace]:unkown}"
      protocol: "https"
      ssl.verification_mode: "none"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-24T11:03:15Z"
  name: filebeat-filebeat-daemonset-config
  namespace: logging
  resourceVersion: "282621761"
  uid: 085fcc99-15ed-4aab-a003-266c6772a73e